name: test

on: [push, pull_request]

jobs:
  tests:
    name: Run tests for (${{ matrix.ruby }} / Rails ${{ matrix.rails }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ruby: [ "3.1", "3.2" ]
        rails: [ "7.0" ]
    steps:
      - uses: actions/checkout@v3
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
      - name: Install gems
        env:
          MATRIX_RAILS_VERSION: ${{ matrix.rails }}
        run: |
          gem install bundler
          bundle install
          export BUNDLE_GEMFILE="${GITHUB_WORKSPACE}/gemfiles/rails_${MATRIX_RAILS_VERSION}.gemfile"
          bundle install --jobs 4 --retry 3
      - name: Run tests
        run: bundle exec ./bin/test
